spring:
  application:
    name: StudentFeesMS

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
